---
name: ALPM
version: 0.02
author:
  - 'Justin Davis <jrcd83@gmail.com>'
abstract: "Perl OO version of libalpm, Archlinux's packaging system"
license: perl
resources:
  license: http://dev.perl.org/licenses/
build_requires:
  ExtUtils::CBuilder: 0
  Test::More: 0
provides:
  ALPM:
    file: lib/ALPM.pm
    version: 0.02
  ALPM::DB:
    file: lib/ALPM/DB.pm
  ALPM::LoadConfig:
    file: lib/ALPM/LoadConfig.pm
  ALPM::Package:
    file: lib/ALPM/Package.pm
  ALPM::PackageFree:
    file: lib/ALPM/PackageFree.pm
generated_by: Module::Build version 0.280801
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
